{
  "swagger": "2.0",
  "info": {
    "title": "Spotify",
    "description": "Custom connector around the Spotify API.\nFunctionalities available around users, playlists, albums, tracks.",
    "version": "1.0"
  },
  "host": "api.spotify.com",
  "basePath": "/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/me/player/currently-playing": {
      "get": {
        "summary": "Get the User's Currently Playing Track",
        "operationId": "GetUserCurrentPlayingTrack",
        "description": "Get the object currently being played on the user\u2019s Spotify account."
      }
    },
    "/me/player/play": {
      "put": {
        "summary": "Start/Resume Playback",
        "operationId": "StartResumePlayback",
        "description": "Start a new context or resume current playback on the user\u2019s active device. (Spotify PREMIUM)"
      }
    },
    "/me/playlists": {
      "get": {
        "summary": "Get a List of Current User's Playlists",
        "operationId": "GetListCurrentUserPlaylists",
        "description": "Get a list of the playlists owned or followed by the current Spotify user."
      }
    },
    "/browse/new-releases": {
      "get": {
        "summary": "Get All New Releases",
        "operationId": "GetAllNewReleases",
        "description": "Get a list of new album releases featured in Spotify."
      }
    },
    "/search": {
      "get": {
        "summary": "Search for an Item",
        "description": "Get Spotify Catalog information about albums, artists, playlists, tracks, shows or episodes that match a keyword string.",
        "operationId": "SearchAnItem"
      }
    },
    "/browse/featured-playlists": {
      "get": {
        "summary": "Get All Featured Playlists",
        "operationId": "GetAllFeaturedPlaylists",
        "description": "Get a list of Spotify featured playlists."
      }
    },
    "/browse/categories": {
      "get": {
        "summary": "Get All Categories",
        "operationId": "GetAllCategories",
        "description": "Get a list of categories used to tag items in Spotify."
      }
    },
    "/browse/categories/{category_id}": {
      "get": {
        "summary": "Get a Category",
        "operationId": "GetCategory",
        "description": "Get a single category used to tag items in Spotify."
      }
    },
    "/browse/categories/{category_id}/playlists": {
      "get": {
        "summary": "Get a Category's Playlists",
        "operationId": "GetCategoryPlaylists",
        "description": "Get a list of Spotify playlists tagged with a particular category."
      }
    },
    "/users/{user_id}/playlists": {
      "post": {
        "summary": "Create a Playlist",
        "operationId": "CreatePlaylist",
        "description": "Create a playlist for a Spotify user. (The playlist will be empty until you add tracks.)"
      }
    },
    "/playlists/{playlist_id}": {
      "get": {
        "summary": "Get a Playlist",
        "operationId": "GetPlaylist",
        "description": "Get a playlist owned by a Spotify user."
      },
      "put": {
        "summary": "Change a Playlist's Details",
        "description": "Change a playlist\u2019s name and public/private state. (The user must, of course, own the playlist.)",
        "operationId": "ChangePlaylistDetails"
      }
    },
    "/playlists/{playlist_id}/tracks": {
      "get": {
        "summary": "Get a Playlist's Items",
        "operationId": "GetPlaylistItems",
        "description": "Get full details of the items of a playlist owned by a Spotify user."
      },
      "delete": {
        "summary": "Remove Items from a Playlist",
        "operationId": "RemoveItemsFromPlaylist",
        "description": "Remove one or more items from a user\u2019s playlist."
      },
      "post": {
        "summary": "Add Items to a Playlist",
        "description": "Add one or more items to a user\u2019s playlist.",
        "operationId": "AddItemsToPlaylist"
      }
    },
    "/playlists/{playlist_id}/images": {
      "get": {
        "summary": "Get a Playlist Cover Image",
        "operationId": "GetPlaylistCoverImage",
        "description": "Get the current image associated with a specific playlist."
      }
    },
    "/tracks/{id}": {
      "get": {
        "summary": "Get a Track",
        "operationId": "GetTrack",
        "description": "Get Spotify catalog information for a single track identified by its unique Spotify ID."
      }
    },
    "/me": {
      "get": {
        "summary": "Get Current User's Profile",
        "operationId": "GetCurrentUserProfile",
        "description": "Get detailed profile information about the current user (including the current user\u2019s username)."
      }
    },
    "/users/{user_id}": {
      "get": {
        "summary": "Get a User's Profile",
        "operationId": "GetUserProfile",
        "description": "Get public profile information about a Spotify user."
      }
    },
    "/playlists/{playlist_id}/followers": {},
    "/playlists/{playlist_id}/followers/contains": {
      "get": {
        "summary": "Check if Users Follow a Playlist",
        "operationId": "CheckIfUsersFollowPlaylist",
        "description": "Check to see if one or more Spotify users are following a specified playlist."
      }
    },
    "/me/following": {},
    "/artists": {
      "get": {
        "summary": "Get Multiple Artists",
        "operationId": "GetMultipleArtists",
        "description": "Get Spotify catalog information for several artists based on their Spotify IDs."
      }
    },
    "/artists/{id}": {
      "get": {
        "summary": "Get an Artist",
        "operationId": "GetAnArtist",
        "description": "Get Spotify catalog information for a single artist identified by their unique Spotify ID."
      }
    },
    "/artists/{id}/albums": {
      "get": {
        "summary": "Get an Artist's Albums",
        "operationId": "GetAnArtistAlbums",
        "description": "Get Spotify catalog information about an artist\u2019s albums."
      }
    }
  },
  "securityDefinitions": {
    "oauth2_auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://accounts.spotify.com/authorize",
      "tokenUrl": "https://accounts.spotify.com/api/token",
      "scopes": {
        "user-read-currently-playing user-modify-playback-state user-read-playback-state playlist-modify-private playlist-modify-public playlist-read-collaborative playlist-read-private user-follow-modify user-follow-read user-library-modify user-library-read": "user-read-currently-playing user-modify-playback-state user-read-playback-state playlist-modify-private playlist-modify-public playlist-read-collaborative playlist-read-private user-follow-modify user-follow-read user-library-modify user[...]"
      }
    }
  },
  "security": [
    {
      "oauth2_auth": [
        "user-read-currently-playing user-modify-playback-state user-read-playback-state playlist-modify-private playlist-modify-public playlist-read-collaborative playlist-read-private user-follow-modify user-follow-read user-library-modify user-library-read"
      ]
    }
  ],
  "tags": []
}